/*1*/

SELECT A.NOMBRE, A.COSTEBASICO 
FROM TITULACION t , ASIGNATURA a 
WHERE T.IDTITULACION = A.IDTITULACION 
ORDER BY A.COSTEBASICO DESC, A.NOMBRE;

/*2*/

SELECT P2.NOMBRE , P2.APELLIDO 
FROM PROFESOR p , PERSONA p2 
WHERE P.DNI = P2.DNI ;

/*3*/

SELECT A.NOMBRE 
FROM PROFESOR p , ASIGNATURA a , PERSONA pER
WHERE P.DNI = PER.DNI , a.IDPROFESOR = p.IDPROFESOR  
AND PER.CIUDAD LIKE 'Sevilla';

/*4*/

SELECT P.NOMBRE 
FROM ALUMNO a, PERSONA p 
WHERE A.DNI = P.DNI ;

/*5*/

SELECT p. DNI , P.NOMBRE , P.APELLIDO 
FROM ALUMNO a, PERSONA p 
WHERE A.DNI = P.DNI AND P.CIUDAD LIKE 'Sevilla';

/*6*/

SELECT P.DNI , P.NOMBRE , P.APELLIDO 
FROM ALUMNO_ASIGNATURA aa , ASIGNATURA a , ALUMNO a2 , PERSONA p 
WHERE aa.IDASIGNATURA = a.IDASIGNATURA AND A2.IDALUMNO = AA.IDALUMNO  AND A2.DNI = P.DNI
AND A.NOMBRE LIKE 'Seguridad Vial';

/*7*/

SELECT T.IDTITULACION 
FROM ALUMNO a , TITULACION t , ALUMNO_ASIGNATURA aa, ASIGNATURA a2  
WHERE AA.IDALUMNO = A.IDALUMNO AND AA.IDASIGNATURA = A2.IDASIGNATURA 
AND T.IDTITULACION = A2.IDTITULACION 
AND A.DNI LIKE '20202020A';

/*8*/

SELECT a.NOMBRE 
FROM ASIGNATURA a, ALUMNO_ASIGNATURA aa , ALUMNO a2 , PERSONA p  
WHERE P.DNI = A2.DNI AND A2.IDALUMNO = AA.IDALUMNO AND A.IDASIGNATURA = AA.IDASIGNATURA 
AND P.NOMBRE LIKE 'Rosa' AND p.APELLIDO LIKE 'Garcia';

/*9*/

SELECT a.DNI 
FROM ALUMNO a , PROFESOR p , ASIGNATURA a2 , ALUMNO_ASIGNATURA aa , PERSONA p2 
WHERE a.IDALUMNO = aa.IDALUMNO AND aa.IDASIGNATURA = a2.IDASIGNATURA AND a2.IDPROFESOR = p.IDPROFESOR AND p.DNI = p2.DNI 
AND p2.NOMBRE LIKE 'Jorge' AND p2.APELLIDO LIKE 'Saenz';

/*10 PENDIENTE CORREGIR*/

SELECT a.DNI , p2.NOMBRE , p2.APELLIDO 
FROM ALUMNO a , PROFESOR p , ASIGNATURA a2 , ALUMNO_ASIGNATURA aa , PERSONA p2 
WHERE a.IDALUMNO = aa.IDALUMNO AND aa.IDASIGNATURA = a2.IDASIGNATURA AND a2.IDPROFESOR = p.IDPROFESOR AND p.DNI = p2.DNI
AND a.DNI = p2.DNI 
AND p2.NOMBRE LIKE 'Jorge' AND p2.APELLIDO LIKE 'Saenz';

/*11*/

SELECT t.NOMBRE 
FROM TITULACION t , ASIGNATURA a 
WHERE t.IDTITULACION = a.IDTITULACION 
AND a.CREDITOS = 4;

/*12*/

SELECT a.NOMBRE AS Nombre_Asignatura, a.CREDITOS , t.NOMBRE AS Nombre_Titulacion
FROM ASIGNATURA a , TITULACION t 
WHERE t.IDTITULACION = a.IDTITULACION 
AND a.CUATRIMESTRE = 1;

/*13*/

SELECT a.NOMBRE AS Nombre_Asignatura, a.COSTEBASICO , p.NOMBRE 
FROM ASIGNATURA a , ALUMNO_ASIGNATURA aa , ALUMNO alu, PERSONA p 
WHERE a.IDASIGNATURA = aa.IDASIGNATURA AND aa.IDALUMNO = alu.IDALUMNO 
AND alu.DNI = p.DNI 
AND a.CREDITOS > 4.5;


/*14*/

SELECT p2.NOMBRE 
FROM PROFESOR p , ASIGNATURA a , PERSONA p2 
WHERE a.IDPROFESOR = p.IDPROFESOR AND p2.DNI = p.DNI 
AND a.COSTEBASICO BETWEEN 25 AND 35;

/*15*/

SELECT p.NOMBRE 
FROM ALUMNO_ASIGNATURA aa , PERSONA p , ALUMNO a 
WHERE aa.IDALUMNO = a.IDALUMNO AND a.DNI = p.DNI 
AND (aa.IDASIGNATURA = '150212' OR aa.IDASIGNATURA = '130113');

/*16*/

SELECT a.NOMBRE AS Nombre_Asignatura, t.NOMBRE AS TITULACION
FROM ASIGNATURA a , TITULACION t 
WHERE a.IDTITULACION = t.IDTITULACION 
AND a.CUATRIMESTRE = 2 AND a.CREDITOS != 6;

/*17*/

SELECT a.NOMBRE , a.CREDITOS*10 AS NUM_HORAS, alu.DNI AS DNI_ALUMNO
FROM ASIGNATURA a , ALUMNO_ASIGNATURA aa , ALUMNO alu
WHERE aa.IDASIGNATURA  = a.IDASIGNATURA AND aa.IDALUMNO = alu.IDALUMNO;


/*18*/

SELECT p.NOMBRE 
FROM PERSONA p , ALUMNO a , ALUMNO_ASIGNATURA aa 
WHERE p.DNI = a.DNI AND a.IDALUMNO = aa.IDALUMNO 
AND p.VARON = 0 AND p.CIUDAD LIKE 'Sevilla';

/*19*/

SELECT a.NOMBRE 
FROM ASIGNATURA a , PROFESOR p 
WHERE p.IDPROFESOR = a.IDPROFESOR 
AND p.IDPROFESOR = 'P101' AND a.CURSO = 1;

/*20*/

SELECT p.NOMBRE 
FROM ALUMNO_ASIGNATURA aa , ALUMNO a , PERSONA p 
WHERE aa.IDALUMNO = a.IDALUMNO AND a.DNI = p.DNI 
AND aa.NUMEROMATRICULA >= 3;





















