/*1*/
SELECT a.NOMBRE ,a.CREDITOS 
FROM ASIGNATURA a;

/*2*/

SELECT DISTINCT a.CREDITOS 
FROM ASIGNATURA a;

/*3*/

SELECT *
FROM PERSONA p;

/*4*/

SELECT DISTINCT a.NOMBRE , a.CREDITOS 
FROM ASIGNATURA a 
WHERE a.CUATRIMESTRE = 1;

/*5*/

SELECT P.NOMBRE , P.APELLIDO 
FROM PERSONA p 
WHERE P.FECHA_NACIMIENTO < TO_DATE ('01/01/1975', 'DD/MM/YYYY');

/*6*/

SELECT A.NOMBRE , A.COSTEBASICO 
FROM ASIGNATURA a 
WHERE a.CREDITOS > 4.5;

/*7*/

SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE a.COSTEBASICO BETWEEN 25 AND 35;

/*8*/

SELECT DISTINCT aa.IDALUMNO 
FROM ALUMNO_ASIGNATURA aa 
WHERE (aa.IDASIGNATURA ='150212' OR aa.IDASIGNATURA='130113');

/*9*/

SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE (a.CUATRIMESTRE ='2' AND a.CREDITOS != 6);

/*10*/

SELECT p.NOMBRE , p.APELLIDO 
FROM PERSONA p 
WHERE p.APELLIDO LIKE 'G%';

/*11*/

SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE a.IDTITULACION IS NULL;

/*12*/

SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE a.IDTITULACION IS not NULL;

/*13*/

SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE (a.COSTEBASICO*a.CREDITOS)>8 ;

/*14*/

SELECT a.NOMBRE , (a.CREDITOS*10) AS TOTAL_HORAS
FROM ASIGNATURA a;

/*15*/

SELECT *
FROM ASIGNATURA a 
WHERE a.CUATRIMESTRE='2' ORDER BY a.IDASIGNATURA;

/*16*/

SELECT p.NOMBRE 
FROM PERSONA p 
WHERE (p.CIUDAD LIKE 'MADRID' AND p.VARON = 0);

/*17*/

SELECT  p.NOMBRE , p.TELEFONO 
FROM PERSONA p 
WHERE p.TELEFONO LIKE '91%';

/*18*/

SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE a.NOMBRE LIKE '%pro%';

/*19*/

SELECT a.NOMBRE 
FROM ASIGNATURA a 
WHERE a.CURSO = 1 AND a.IDPROFESOR LIKE 'P101';

/*20*/

SELECT aa.IDALUMNO , IDASIGNATURA 
FROM ALUMNO_ASIGNATURA aa
WHERE aa.NUMEROMATRICULA > 3;

/*21*/

SELECT a.NOMBRE , a.COSTEBASICO , a.COSTEBASICO*1.10 AS PRECIO_1_REPETICION, 
a.COSTEBASICO*1.30 AS PRECIO_2_REPETICION,
a.COSTEBASICO*1.60 AS PRECIO_3_REPETICION
FROM ASIGNATURA a;

/*22*/

SELECT *
FROM PERSONA p 
WHERE EXTRACT (YEAR FROM p.FECHA_NACIMIENTO)<1970;

/*23*/

SELECT DISTINCT pro.IDPROFESOR 
FROM PERSONA p , PROFESOR pro
WHERE p.DNI = pro.DNI ;

/*24*/

SELECT DISTINCT aa.IDALUMNO 
FROM ALUMNO_ASIGNATURA aa 
WHERE aa.IDASIGNATURA = '130122';

/*25*/

SELECT DISTINCT aa.IDASIGNATURA 
FROM ALUMNO_ASIGNATURA aa;

/*26*/

SELECT a.NOMBRE  
FROM ASIGNATURA a 
WHERE a.CREDITOS >4
AND (a.CUATRIMESTRE = 1 OR a.CURSO = 1);

/*27*/

SELECT DISTINCT t.IDTITULACION 
FROM ASIGNATURA a , TITULACION t 
WHERE a.IDTITULACION = t.IDTITULACION ;

/*28*/

SELECT p.DNI 
FROM PERSONA p 
WHERE LOWER(p.APELLIDO) LIKE '%g%' ;

/*29*/

SELECT *
FROM PERSONA p 
WHERE EXTRACT (YEAR FROM p.FECHA_NACIMIENTO)>1970
AND p.CIUDAD LIKE 'M%' AND p.VARON = 1;