CREATE TABLE ALUMNOS
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(20),
APELLIDO1 VARCHAR2(20),
APELLIDO2 VARCHAR2(20),
DIRECCION VARCHAR2(40),
FECHANACIMIENTO DATE,
SEXO VARCHAR2(1),

CONSTRAINT PK_ALUMNOS PRIMARY KEY (DNI),
CONSTRAINT CHK1_SEXO CHECK (SEXO IN ('H','M'))
);

CREATE TABLE PROFESOR
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(20),
APELLIDO1 VARCHAR2(20),
APELLIDO2 VARCHAR2(20),
DIRECCION VARCHAR2(40),
TITULACION VARCHAR2(30),
SUELDO NUMBER(5),
CONSTRAINT PK_PROFESOR PRIMARY KEY (DNI)
);


CREATE TABLE CURSO
(
CODIGO VARCHAR2(10),
NOMBRE VARCHAR2(20),
NUM_MAX_ALUMNOS_RECOMENDADOS NUMBER(3),
DNIPROFESOR VARCHAR2(10),
FECHAINICIO DATE,
FECHAFIN DATE,
NUMHORASCURSO NUMBER(5),
CONSTRAINT PK_CURSO PRIMARY KEY (CODIGO),
CONSTRAINT FK1_PROFESOR FOREIGN KEY (DNIPROFESOR) REFERENCES PROFESOR(DNI)
);


INSERT INTO PROFESOR 
VALUES ('32432455','JUAN', 'ARCH', 'LOPEZ', 'PUERTA NEGRA, 4', 'ING. INFORMATICA', 7500);

INSERT INTO PROFESOR
VALUES ('43215643','MARIA', 'OLIVA', 'RUBIO', 'JUAN ALFONSO, 32', 'LDA. FIL INGLESA', 5400);

INSERT INTO CURSO
VALUES ('1', 'INGLES BASICO', 15, '43215643', TO_DATE('01/11/00', 'DD/MM/YY'), TO_DATE('22-DIC-00', 'DD-MONTH-YY'), 120);

INSERT INTO CURSO
VALUES ('2', 'ADMINISTRACION LINUX', NULL, '32432455', TO_DATE('01-SEP-00', 'DD-MONTH-YY'), NULL, 80);

INSERT ALUMNOS
VALUES('123523')