alter session set "_oracle_script"=true;  
create user CABALLOS identified by CABALLOS;
GRANT CONNECT, RESOURCE, DBA TO CABALLOS;

CREATE TABLE CABALLOS
(
CODCABALLO VARCHAR2(4),
NOMBRE VARCHAR2(20) NOT NULL,
PESO NUMBER(3),
FECHANACIMIENTO DATE,
PROPIETARIO VARCHAR2(25),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_CODCABALLO PRIMARY KEY (CODCABALLO),
CONSTRAINT CHK1_PESO CHECK (PESO BETWEEN 240 AND 300),
CONSTRAINT CHK2_FECHANACIMIENTO CHECK (EXTRACT(YEAR FROM FECHANACIMIENTO)>2000),
CONSTRAINT CHK3_NACIONALIDAD CHECK (NACIONALIDAD=(UPPER(NACIONALIDAD)))
);

CREATE TABLE CARRERAS
(
CODCARRERA VARCHAR2(4),
FECHAYHORA DATE,
IMPORTEPREMIO NUMBER(6),
APUESTALIMITE NUMBER(7,2),
CONSTRAINT PK_CARRERAS PRIMARY KEY (CODCARRERA),
CONSTRAINT CHK_FECHAYHORA CHECK (TO_CHAR(FECHAYHORA)>TO_CHAR('09:00','HH:MM')AND TO_CHAR(FECHAYHORA)<TO_CHAR('14:30','HH:MM')),
CONSTRAINT CHK2_APUESTA CHECK (APUESTALIMITE < 20000)
);

CREATE TABLE PARTICIPACIONES
(
CODCABALLO VARCHAR2(4),
CODCARRERA VARCHAR2(4),
DORSAL NUMBER(2) NOT NULL,
JOCKEY VARCHAR2(10) NOT NULL,
POSICIONFINAL NUMBER(2),
CONSTRAINT PK_PARTICIPACIONES PRIMARY KEY (CODCABALLO, CODCARRERA),
CONSTRAINT FK_CODCABALLO FOREIGN KEY (CODCABALLO) REFERENCES CABALLOS(CODCABALLO),
CONSTRAINT FK_CODCARRERA FOREIGN KEY (CODCARRERA) REFERENCES CARRERAS(CODCARRERA),
CONSTRAINT CHK_POSICIONFINAL CHECK (POSICIONFINAL > 0)
);

CREATE TABLE CLIENTES
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(20),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI),
CONSTRAINT CHK_DNI CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}[A-Za-z]{1}$')),
CONSTRAINT CHK2_NACIONALIDAD CHECK (NACIONALIDAD=UPPER(NACIONALIDAD))
);

CREATE TABLE APUESTAS
(
DNICLIENTE VARCHAR2(10),
CODCABALLO VARCHAR2(4),
CODCARRERA VARCHAR2(4),
IMPORTE NUMBER(6) DEFAULT 300,
TANTOPORUNO NUMBER(6,2),
CONSTRAINT PK_APUESTAS PRIMARY KEY (DNICLIENTE, CODCABALLO, CODCARRERA),
CONSTRAINT FK_DNICLIENTE FOREIGN KEY (DNICLIENTE) REFERENCES CLIENTES(DNI) ON DELETE CASCADE,
CONSTRAINT FK_CODCABALLO_APUESTAS FOREIGN KEY (CODCABALLO) REFERENCES CABALLOS(CODCABALLO) ON DELETE CASCADE,
CONSTRAINT FK_CODCARRERA_APUESTAS FOREIGN KEY (CODCARRERA) REFERENCES CARRERAS(CODCARRERA) ON DELETE CASCADE,
CONSTRAINT CHK_IMPORTE CHECK (IMPORTE > 1)
);

/*INSERT INTO CLIENTES 
VALUES ('26987142C', 'WILLY', 'ESCOCES');*/

INSERT INTO CABALLOS
VALUES ('2145', 'ELPESADO', 300, TO_DATE('20-07-2001', 'DD-MM-YYYY'), 'YERAY', 'ESPAÑOLA');

/*INSERT INTO CARRERAS 
VALUES ('1', TO_DATE('17-01-2023-10:30', 'DD-MM-YYY-H24:MI'), 1000, 15000);*/

INSERT INTO CABALLOS
VALUES ('2', 'ELQUEVASEGUNDO', 240, TO_DATE('20-07-2010', 'DD-MM-YYYY'), 'YERAY', 'ESPAÑOLA');

INSERT INTO CARRERAS 
VALUES ('C6', NULL, 800, 150);

INSERT INTO PARTICIPACIONES 
VALUES (2, 'C6', 2, 'YERAY', NULL);

INSERT INTO PARTICIPACIONES 
VALUES (2145, 'C6', 3, 'JESUS', NULL);

INSERT INTO CARRERAS 
VALUES ('C7', NULL, 1000, 800);

INSERT INTO CARRERAS 
VALUES ('C1', NULL, 600, 1500);

ALTER TABLE CABALLOS DROP COLUMN PROPIETARIO;

ALTER TABLE PARTICIPACIONES ADD CONSTRAINT CHK_NOMBRE CHECK (REGEXP_LIKE(JOCKEY,'^[A-Z]'));

/*ALTER TABLE CARRERAS ADD CONSTRAINT CHK2_FECHA CHECK ;*/

ALTER TABLE CABALLOS ADD CONSTRAINT CHK5_NACIONALIDAD CHECK (NACIONALIDAD IN ('ESPAÑOLA','BRITANICA','ARABE'));

DELETE FROM CARRERAS WHERE NOT EXISTS (SELECT * FROM PARTICIPACIONES);

ALTER TABLE CLIENTES ADD CODIGO VARCHAR2(10) NOT NULL;

INSERT INTO CARRERAS 
VALUES ('C66', NULL, 800, 150);

UPDATE PARTICIPACIONES SET CODCARRERA='C66' WHERE CODCARRERA='C6';

DELETE FROM CARRERAS WHERE CODCARRERA='C6';

/*DROP TABLE APUESTAS CASCADE CONSTRAINTS;
DROP TABLE CABALLOS CASCADE CONSTRAINTS;
DROP TABLE CARRERAS CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE PARTICIPACIONES  CASCADE CONSTRAINTS;*/

DROP USER CABALLOS CASCADE;





