CREATE TABLE BARCOS
(
MATRICULA VARCHAR(10),
NOMBRE VARCHAR(20),
CLASE VARCHAR(20),
ARMADOR VARCHAR(20),
CAPACIDAD integer(10),
NACIONALIDAD VARCHAR(20),
CONSTRAINT PK_BARCOS PRIMARY KEY (MATRICULA)
);

CREATE TABLE CALADERO
(
CODIGO VARCHAR(10),
NOMBRE VARCHAR(20),
UBICACION VARCHAR(20),
ESPECIEPRINCIPAL VARCHAR(20),
CONSTRAINT PK_CALADERO PRIMARY KEY (CODIGO)
);

CREATE TABLE ESPECIE
(
CODIGO VARCHAR(10),
NOMBRE VARCHAR(10),
TIPO VARCHAR(10),
CUPOPORBARCO integer(10),
CALADEROPRINCIPAL VARCHAR(20),
CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO),
CONSTRAINT FK1_CALADEROPRINCIPAL FOREIGN KEY (CALADEROPRINCIPAL) REFERENCES CALADERO(CODIGO)
);

CREATE TABLE LOTES
(
CODIGO VARCHAR(10),
MATRICULA VARCHAR(10),
NUMKILOS integer(10),
PRECIOPORKILOSALIDA integer(20.3),
PRECIOPORKILOADJUDICADO integer(20.3),
FECHAVENTE DATE NOT NULL,
CODESPECIE VARCHAR(10),
CONSTRAINT PK_LOTES PRIMARY KEY (CODIGO),
CONSTRAINT FK1_MATRICULA FOREIGN KEY (MATRICULA) REFERENCES BARCOS(MATRICULA) ON DELETE CASCADE,
CONSTRAINT FK2_CODESPECIE FOREIGN KEY (CODESPECIE) REFERENCES ESPECIE(CODIGO) ON DELETE CASCADE
);

CREATE TABLE FECHAS_CAPTURAS_PERMITIDAS 
(
CODESPECIE VARCHAR(10),
CODCALADERO VARCHAR(10),
FECHAINICIAL DATE,
FECHAFINAL DATE,
CONSTRAINT PK_FECHASCAPTURASPERMITIDAS PRIMARY KEY (CODESPECIE, CODCALADERO),
CONSTRAINT FK1_CODESPECIE FOREIGN KEY (CODESPECIE) REFERENCES ESPECIE(CODIGO),
CONSTRAINT FK2_CODCALADERO FOREIGN KEY (CODCALADERO) REFERENCES CALADERO(CODIGO)
)


ALTER TABLE CALADERO ADD CONSTRAINT FK1_ESPECIEPRINCIPAL FOREIGN KEY (ESPECIEPRINCIPAL) REFERENCES ESPECIE(CODIGO);
ALTER TABLE BARCOS ADD CONSTRAINT CHK1_MATRICULA CHECK (REGEXP_LIKE(MATRICULA, '^[A-Z]{2}-[0-9]{4}$'));
ALTER TABLE LOTES ADD CONSTRAINT CHK2_PRECIOPORKILOADJUDICADO CHECK (PRECIOPORKILOADJUDICADO>PRECIOPORKILOSALIDA);
ALTER TABLE LOTES ADD CONSTRAINT CHK3_NUMKILOSPRECIO CHECK (NUMKILOS > 0 AND PRECIOPORKILOSALIDA > 0 AND PRECIOPORKILOADJUDICADO > 0);
ALTER TABLE CALADERO ADD CONSTRAINT CHK1_MAYUSCNOMBRE CHECK (UPPER(NOMBRE) = NOMBRE);
ALTER TABLE CALADERO ADD CONSTRAINT CHK1_MAYUSCUBICACION CHECK (UPPER(UBICACION) = UBICACION);
ALTER TABLE FECHAS_CAPTURAS_PERMITIDAS ADD CONSTRAINT CHK1_FECHASPERMITIDAS CHECK (NOT (fechainicial BETWEEN STR_TO_DATE('2022-02-02', 'YYYY-MM-DD') AND STR_TO_DATE('2022-03-28', 'YYYY-MM-DD')) AND NOT (fechafinal BETWEEN STR_TO_DATE('2022-02-02', 'YYYY-MM-DD') AND STR_TO_DATE('2022-03-28', 'YYYY-MM-DD')));
ALTER TABLE CALADERO ADD NOMBRECIENTIFICO VARCHAR(20);
