/*alter session set "_oracle_script"=true;  
create user MARIPOSAS identified by MARIPOSAS;
GRANT CONNECT, RESOURCE, DBA TO MARIPOSAS;*/

CREATE TABLE FAMILIA
(
NOMBRE VARCHAR2(20),
CARACTERISTICAS VARCHAR2(80),
CONSTRAINT PK_FAMILIA PRIMARY KEY (NOMBRE)
);

CREATE TABLE GENERO
(
NOMBRE VARCHAR2(20),
CARACTERISTICAS VARCHAR(80),
NOMBRE_FAMILIA VARCHAR2(20),
CONSTRAINT PK_GENERO PRIMARY KEY (NOMBRE),
CONSTRAINT FK_NOMBRE_FAMILIA FOREIGN KEY (NOMBRE_FAMILIA) REFERENCES FAMILIA(NOMBRE)
);

CREATE TABLE ESPECIE
(
NOMBRE VARCHAR2(20),
CARACTERISTICAS VARCHAR2(80),
NOMBRE_GENERO VARCHAR2(20),
CONSTRAINT PK_ESPECIE PRIMARY KEY (NOMBRE),
CONSTRAINT FK_NOMBRE_GENERO FOREIGN KEY (NOMBRE_GENERO) REFERENCES GENERO(NOMBRE)
);

CREATE TABLE PERSONA
(
DNI VARCHAR2(9),
NOMBRE VARCHAR2(20),
DIRECCION VARCHAR2(50),
TELEFONO VARCHAR2(12),
USUARIO VARCHAR2(20),
CONSTRAINT FK_PERSONA PRIMARY KEY (DNI)
);

CREATE TABLE COLECCION
(
DNI VARCHAR2(9),
PRECIO NUMBER(7,2),
FECHA_INICIO DATE,
NUM_EJEMPLARES NUMBER (5),
CONSTRAINT PK_COLECCION PRIMARY KEY (DNI),
CONSTRAINT FK_DNI_PROPIETARIO FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)

);

CREATE TABLE ZONA
(
NOMBRE VARCHAR2(20),
LOCALIDAD VARCHAR2(50),
EXTENSION NUMBER(2),
PROTEGIDA CHAR,
CONSTRAINT PK_ZONA PRIMARY KEY (NOMBRE)
);

CREATE TABLE EJEMPLAR_MARIPOSA
(
PRECIO_EJEMPLAR NUMBER(7,2),
NOMBRE_COMUN VARCHAR2(20),
NOMBRE_ESPECIE VARCHAR2(20),
NOMBRE_ZONA VARCHAR2(20),
HORA_CAPTURA TIMESTAMP,
FECHA_CAPTURA DATE,
DNI_CAPTURA VARCHAR2(9),
FECHA_COLECCION DATE,

CONSTRAINT PK_EJEMPLAR_MARIPOSA PRIMARY KEY (HORA_CAPTURA, FECHA_CAPTURA),
CONSTRAINT FK_NOMBRE_ESPECIE FOREIGN KEY (NOMBRE_ESPECIE) REFERENCES ESPECIE(NOMBRE),
CONSTRAINT FK_DNI_CAPTURA FOREIGN KEY (DNI_CAPTURA) REFERENCES PERSONA(DNI),
CONSTRAINT FK_NOMBRE_ZONA FOREIGN KEY (NOMBRE_ZONA) REFERENCES ZONA(NOMBRE)
);

/*APARTADO A*/

ALTER TABLE EJEMPLAR_MARIPOSA ADD CONSTRAINT CHK1_PRECIO CHECK (PRECIO_EJEMPLAR>0);

ALTER TABLE PERSONA MODIFY USUARIO VARCHAR2(20) UNIQUE;

ALTER TABLE ZONA ADD CONSTRAINT CHK1_ZONA CHECK (PROTEGIDA IN ('SI','NO'));

ALTER TABLE COLECCION ADD CONSTRAINT CHK1_CANTIDAD CHECK (NUM_EJEMPLARES BETWEEN 1 AND 150);

/*APARTADO B*/

ALTER TABLE PERSONA ADD APELLIDOS VARCHAR2(20);

ALTER TABLE ZONA ADD CONSTRAINT CHK2_ZONA CHECK (EXTENSION BETWEEN 100 AND 1500);

ALTER TABLE EJEMPLAR_MARIPOSA DROP CONSTRAINT CHK1_PRECIO;

ALTER TABLE EJEMPLAR_MARIPOSA MODIFY FECHA_CAPTURA DATE DEFAULT SYSDATE;

/*DROP TABLE COLECCION CASCADE CONSTRAINTS;
DROP TABLE EJEMPLAR_MARIPOSA  CASCADE CONSTRAINTS;
DROP TABLE ESPECIE  CASCADE CONSTRAINTS;
DROP TABLE FAMILIA  CASCADE CONSTRAINTS;
DROP TABLE GENERO  CASCADE CONSTRAINTS;
DROP TABLE PERSONA  CASCADE CONSTRAINTS;
DROP TABLE ZONA  CASCADE CONSTRAINTS;
*/
