CREATE TABLE OFICINA
(
CODIGO_OFICINA VARCHAR2(10),
CIUDAD VARCHAR2(30),
PAIS VARCHAR2(50),
REGION VARCHAR2(50),
CODIGO_POSTAL VARCHAR2(10),
TELEFONO VARCHAR2(20),
LINEA_DIRECCION1 VARCHAR2(50),
LINEA_DIRECCION2 VARCHAR2(50),
CONSTRAINT PK_OFICINA PRIMARY KEY (CODIGO_OFICINA)
);

CREATE TABLE EMPLEADO
(
CODIGO_EMPLEADO NUMBER(11),
NOMBRE VARCHAR2(50),
APELLIDO1 VARCHAR2(50),
APELLIDO2 VARCHAR2(50),
EXTENSION VARCHAR2(10),
EMAIL VARCHAR2(100),
CODIGO_OFICINA VARCHAR2(10),
CODIGO_JEFE NUMBER(11),
PUESTO VARCHAR2(50),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO_EMPLEADO),
CONSTRAINT FK_CODIGO_OFICINA FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA),
CONSTRAINT FK_CODIGO_JEFE FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE CLIENTE
(
CODIGO_CLIENTE NUMBER(11),
NOMBRE_CLIENTE VARCHAR2(50),
NOMBRE_CONTACTO VARCHAR2(30),
APELLIDO_CONTACTO VARCHAR2(30),
TELEFONO VARCHAR2(15),
FAX VARCHAR2(15),
LINEA_DIRECCION1 VARCHAR2(50),
LINEA_DIRECCION2 VARCHAR2(50),
CIUDAD VARCHAR2(50),
REGION VARCHAR2(50),
PAIS VARCHAR2(50),
CODIGO_POSTAL VARCHAR2(10),
CODIGO_EMPLEADO_REP_VENTAS NUMBER(11),
LIMITE_CREDITO NUMBER(15,2),
CONSTRAINT PK_CODIGO_CLIENTE PRIMARY KEY (CODIGO_CLIENTE),
CONSTRAINT FK_CODIGO_EMPLEADO_REP_VENTAS FOREIGN KEY (CODIGO_EMPLEADO_REP_VENTAS) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE PAGO
(
CODIGO_CLIENTE NUMBER(11),
FORMA_PAGO VARCHAR2(40),
ID_TRANSACCION VARCHAR2(50),
FECHA_PAGO DATE,
TOTAL NUMBER(15,2),
CONSTRAINT PK_PAGO PRIMARY KEY (ID_TRANSACCION),
CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

CREATE TABLE PEDIDO
(
CODIGO_PEDIDO NUMBER(11),
FECHA_PEDIDO DATE,
FECHA_ESPERADA DATE,
FECHA_ENTREGA DATE,
ESTADO VARCHAR2(15),
COMENTARIOS VARCHAR2(300),
CODIGO_CLIENTE NUMBER(11),
CONSTRAINT PK_PEDIDO PRIMARY KEY (CODIGO_PEDIDO),
CONSTRAINT FK1_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

CREATE TABLE GAMA_PRODUCTO
(
GAMA VARCHAR2(50),
DESCRIPCION_TEXTO VARCHAR2(150),
DESCRIPCION_HTML VARCHAR2(600),
IMAGEN VARCHAR2(256),
CONSTRAINT PK_GAMA_PRODUCTO PRIMARY KEY (GAMA)
);

CREATE TABLE PRODUCTO
(
CODIGO_PRODUCTO VARCHAR2(15),
NOMBRE VARCHAR2(70),
GAMA VARCHAR2(50),
DIMENSIONES VARCHAR2(25),
PROVEEDOR VARCHAR2(50),
DESCRIPCION VARCHAR2(150),
CANTIDAD_EN_STOCK NUMBER(6),
PRECIO_VENTA NUMBER(15,2),
PRECIO_PROVEEDOR NUMBER(15,2),
CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO),
CONSTRAINT FK_GAMA FOREIGN KEY (GAMA) REFERENCES GAMA_PRODUCTO(GAMA)
);

CREATE TABLE DETALLE_PEDIDO
(
CODIGO_PEDIDO NUMBER(11),
CODIGO_PRODUCTO VARCHAR2(15),
CANTIDAD NUMBER(11),
PRECIO_UNIDAD NUMBER(15,2),
NUMERO_LINEA NUMBER(6),
CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (CODIGO_PEDIDO,CODIGO_PRODUCTO),
CONSTRAINT FK1_CODIGO_PRODUCTO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO),
CONSTRAINT FK2_CODIGO_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO_PEDIDO)
);

/*Para la tabla empleados creada en el ejercicio anterior crea una tabla idéntica llamada empleadosbackup. Una vez creada deberas investigar para que con una única sentencia de INSERT seas capaz de insertar en esta nueva tabla, todos los datos de la tabla empleados. De esta forma conseguiríamos una copia de la tabla empleados.*/

CREATE TABLE EMPLEADOSBACKUP
(
CODIGO_EMPLEADO NUMBER(11),
NOMBRE VARCHAR2(50),
APELLIDO1 VARCHAR2(50),
APELLIDO2 VARCHAR2(50),
EXTENSION VARCHAR2(10),
EMAIL VARCHAR2(100),
CODIGO_OFICINA VARCHAR2(10),
CODIGO_JEFE NUMBER(11),
PUESTO VARCHAR2(50),
CONSTRAINT PK_EMPLEADOsbackup PRIMARY KEY (CODIGO_EMPLEADO),
CONSTRAINT FK1_CODIGO_OFICINA FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA),
CONSTRAINT FK1_CODIGO_JEFE FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

INSERT INTO OFICINA 
VALUES (1, 'sevilla', 'españa', 'andalucia', '41008', '650000000', 'julian ruiz', '2');

INSERT INTO EMPLEADO
VALUES (1, 'juan', 'garcia', 'saldaña', '501', 'uno@queesta.com', 1, 1, 'empleado');

INSERT INTO EMPLEADOSBACKUP  SELECT * FROM EMPLEADO ;
