CREATE TABLE OFICINA
(
CODIGO_OFICINA VARCHAR(10),
CIUDAD VARCHAR(30),
PAIS VARCHAR(50),
REGION VARCHAR(50),
CODIGO_POSTAL VARCHAR(10),
TELEFONO VARCHAR(20),
LINEA_DIRECCION1 VARCHAR(50),
LINEA_DIRECCION2 VARCHAR(50),
CONSTRAINT PK_OFICINA PRIMARY KEY (CODIGO_OFICINA)
);

CREATE TABLE EMPLEADO
(
CODIGO_EMPLEADO INTEGER(11),
NOMBRE VARCHAR(50),
APELLIDO1 VARCHAR(50),
APELLIDO2 VARCHAR(50),
EXTENSION VARCHAR(10),
EMAIL VARCHAR(100),
CODIGO_OFICINA VARCHAR(10),
CODIGO_JEFE INTEGER(11),
PUESTO VARCHAR(50),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO_EMPLEADO),
CONSTRAINT FK_CODIGO_OFICINA FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA),
CONSTRAINT FK_CODIGO_JEFE FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE CLIENTE
(
CODIGO_CLIENTE INTEGER(11),
NOMBRE_CLIENTE VARCHAR(50),
NOMBRE_CONTACTO VARCHAR(30),
APELLIDO_CONTACTO VARCHAR(30),
TELEFONO VARCHAR(15),
FAX VARCHAR(15),
LINEA_DIRECCION1 VARCHAR(50),
LINEA_DIRECCION2 VARCHAR(50),
CIUDAD VARCHAR(50),
REGION VARCHAR(50),
PAIS VARCHAR(50),
CODIGO_POSTAL VARCHAR(10),
CODIGO_EMPLEADO_REP_VENTAS INTEGER(11),
LIMITE_CREDITO DECIMAL(15,2),
CONSTRAINT PK_CODIGO_CLIENTE PRIMARY KEY (CODIGO_CLIENTE),
CONSTRAINT FK_CODIGO_EMPLEADO_REP_VENTAS FOREIGN KEY (CODIGO_EMPLEADO_REP_VENTAS) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE PAGO
(
CODIGO_CLIENTE INTEGER(11),
FORMA_PAGO VARCHAR(40),
ID_TRANSACCION VARCHAR(50),
FECHA_PAGO DATE,
TOTAL DECIMAL(15,2),
CONSTRAINT PK_PAGO PRIMARY KEY (ID_TRANSACCION),
CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

CREATE TABLE PEDIDO
(
CODIGO_PEDIDO INTEGER(11),
FECHA_PEDIDO DATE,
FECHA_ESPERADA DATE,
FECHA_ENTREGA DATE,
ESTADO VARCHAR(15),
COMENTARIOS TEXT,
CODIGO_CLIENTE INTEGER(11),
CONSTRAINT PK_PEDIDO PRIMARY KEY (CODIGO_PEDIDO),
CONSTRAINT FK1_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

CREATE TABLE GAMA_PRODUCTO
(
GAMA VARCHAR(50),
DESCRIPCION_TEXTO TEXT,
DESCRIPCION_HTML TEXT,
IMAGEN VARCHAR(256),
CONSTRAINT PK_GAMA_PRODUCTO PRIMARY KEY (GAMA)
);

CREATE TABLE PRODUCTO
(
CODIGO_PRODUCTO VARCHAR(15),
NOMBRE VARCHAR(70),
GAMA VARCHAR(50),
DIMENSIONES VARCHAR(25),
PROVEEDOR VARCHAR(50),
DESCRIPCION VARCHAR(150),
CANTIDAD_EN_STOCK SMALLINT(6),
PRECIO_VENTA DECIMAL(15,2),
PRECIO_PROVEEDOR DECIMAL(15,2),
CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO),
CONSTRAINT FK_GAMA FOREIGN KEY (GAMA) REFERENCES GAMA_PRODUCTO(GAMA)
);

CREATE TABLE DETALLE_PEDIDO
(
CODIGO_PEDIDO INTEGER(11),
CODIGO_PRODUCTO VARCHAR(15),
CANTIDAD INTEGER(11),
PRECIO_UNIDAD DECIMAL(15,2),
NUMERO_LINEA SMALLINT(6),
CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (CODIGO_PEDIDO,CODIGO_PRODUCTO),
CONSTRAINT FK1_CODIGO_PRODUCTO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO),
CONSTRAINT FK2_CODIGO_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO_PEDIDO)
);

