CREATE TABLE EQUIPOS(
CODEQUIPO VARCHAR(4),
NOMBRE VARCHAR(30) NOT NULL,
LOCALIDAD VARCHAR(15),
CONSTRAINT PK_EQUIPOS PRIMARY KEY (CODEQUIPO)
);

CREATE TABLE JUGADORES(
CODJUGADOR VARCHAR(4),
NOMBRE VARCHAR(30),
FECHA_NACIMIENTO DATE,
DEMARCACION VARCHAR(10),
CODEQUIPO VARCHAR(4),
CONSTRAINT PK_JUGADORES PRIMARY KEY (CODJUGADOR),
CONSTRAINT FK1_CODEQUIPO FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPOS(CODEQUIPO),

);

CREATE TABLE PARTIDOS(
CODPARTIDO VARCHAR(4),
CODEQUIPOLOCAL VARCHAR(4),
CODEQUIPOVISITANTE VARCHAR(4),
FECHA DATE,
COMPETICION VARCHAR(4),
JORNADA VARCHAR(20),
CONSTRAINT PK_PARTIDOS PRIMARY KEY (CODPARTIDO),
CONSTRAINT FK1_CODEQUIPOLOCAL FOREIGN KEY (CODEQUIPOLOCAL) REFERENCES EQUIPOS(CODEQUIPO),
CONSTRAINT FK2_CODEQUIPOVISITANTE FOREIGN KEY (CODEQUIPOVISITANTE) REFERENCES EQUIPOS(CODEQUIPO),
CONSTRAINT CHK1_FECHA CHECK (EXTRACT(MONTH FROM FECHA) !=7 OR EXTRACT(MONTH FROM FECHA)!=8 ),
CONSTRAINT CHK2_COMPETICION CHECK (COMPETICION LIKE  'LIGA' OR COMPETICION LIKE 'COPA')
);

CREATE TABLE INDIDENCIAS(
NUMINCIDENCIA VARCHAR(6),
CODPARTIDO VARCHAR(4),
CODJUGADOR VARCHAR(4),
MINUTO intEGER(2),
TIPO VARCHAR(20),
CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUMINCIDENCIA),
CONSTRAINT FK1_CODPARTIDO FOREIGN KEY (CODPARTIDO) REFERENCES PARTIDOS(CODPARTIDO),
CONSTRAINT FK2_CODJUGADOR FOREIGN KEY (CODJUGADOR) REFERENCES JUGADORES(CODJUGADOR),
CONSTRAINT CHK1_MINUTO CHECK (MINUTO BETWEEN 1 AND 100)
);
