-- Apartado 1

INSERT INTO PERSONA 
VALUES ('47349821C', 'JOSE MIGUEL', 'CABRERA SAMPEDRO','Vva RIO Y MINAS', 'ANTONIO MACHADO',69,'650939828',TO_DATE('20/07/1992', 'DD/MM/YYYY'), 1);

INSERT INTO ALUMNO
VALUES ('13', '47349821C')

INSERT INTO ALUMNO_ASIGNATURA 
VALUES ('13', '160002', 1);

-- Apartado 2

INSERT INTO PERSONA 
VALUES ('77222122K', 'MARTA', 'LOPEZ MARTOS','SEVILLA', 'TARFIA',9,'615891432',TO_DATE('22/07/1981', 'DD/MM/YYYY'), 0);

INSERT INTO PROFESOR 
VALUES ('6', '77222122K');

UPDATE ASIGNATURA  SET IDPROFESOR = '6' WHERE IDPROFESOR = 'P117';

DELETE FROM PROFESOR p WHERE IDPROFESOR = 'P117';

-- Apartado 3

CREATE TABLE ALUMNOS_MUYREPETIDORES
(
IDASIGNATURA VARCHAR2(6),
DNI VARCHAR2(11),
NOMBRE VARCHAR2(30),
APELLIDO VARCHAR2(30),
TELEFONO VARCHAR2(9),
CONSTRAINT PK_ALUMNOS_MUYREPETIDORES PRIMARY KEY (IDASIGNATURA, DNI),
CONSTRAINT FK_IDASIGNATURA FOREIGN KEY (IDASIGNATURA) REFERENCES ASIGNATURA(IDASIGNATURA),
CONSTRAINT FK_DNI FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);


SELECT AA.IDASIGNATURA , A.DNI , P.NOMBRE , P.APELLIDO , P.TELEFONO  
FROM ALUMNO_ASIGNATURA aa , ALUMNO a , PERSONA p 
WHERE AA.IDALUMNO = A.IDALUMNO AND A.DNI = P.DNI 
AND NUMEROMATRICULA >=3

INSERT INTO ALUMNOS_MUYREPETIDORES SELECT AA.IDASIGNATURA , A.DNI , P.NOMBRE , P.APELLIDO , P.TELEFONO  
FROM ALUMNO_ASIGNATURA aa , ALUMNO a , PERSONA p 
WHERE AA.IDALUMNO = A.IDALUMNO AND A.DNI = P.DNI 
AND NUMEROMATRICULA >=3 ;

-- Apartado 4

ALTER TABLE ALUMNOS_MUYREPETIDORES ADD OBSERVACIONES VARCHAR2(200);

UPDATE ALUMNOS_MUYREPETIDORES SET OBSERVACIONES = 'Se encuentra en seguimiento' WHERE OBSERVACIONES IS NULL 
SELECT *
FROM ALUMNOS_MUYREPETIDORES am , PERSONA p
WHERE AM.DNI = P.DNI AND AM.TELEFONO LIKE '%20%' AND P.CIUDAD LIKE 'Sevilla';

-- Apartado 5

DELETE FROM ALUMNOS_MUYREPETIDORES am WHERE SELECT * 
FROM PERSONA p , ALUMNOS_MUYREPETIDORES am 
WHERE AM.DNI = P.DNI AND EXTRACT(YEAR FROM P.FECHA_NACIMIENTO)='1971'; 

-- Apartado 6

CREATE TABLE RESUMEN_TITULACIONES
(
NOMBRE_TITULACION VARCHAR2(20),
NUMEROASIGNATURAS NUMBER(2),
CONSTRAINT PK_RESUMEN_TITULACIONES PRIMARY KEY (NOMBRE_TITULACION)
);

SELECT T.NOMBRE , COUNT(A.IDASIGNATURA)
FROM TITULACION t , ASIGNATURA a 
WHERE T.IDTITULACION = A.IDTITULACION 
GROUP BY T.NOMBRE ;

INSERT INTO RESUMEN_TITULACIONES SELECT T.NOMBRE , COUNT(A.IDASIGNATURA)
FROM TITULACION t , ASIGNATURA a 
WHERE T.IDTITULACION = A.IDTITULACION 
GROUP BY T.NOMBRE ;

--Apartado 7

CREATE TABLE JUEGODETRONOS
(
COD_PERSONAJE NUMBER(4),
NOMBRE VARCHAR2(20),
EDAD NUMBER(3),
CONSTRAINT PK_JUEGODETRONOS PRIMARY KEY (COD_PERSONAJE)
);

--CREATE SEQUENCE SQ1

--Apartado 8

DELETE FROM JUEGODETRONOS WHERE EDAD<18 AND NOMBRE LIKE 'A%';

--Apartado 9

UPDATE PERSONA p SET P.FECHA_NACIMIENTO = TO_DATE('22/07/1980', 'DD/MM/YYYY') WHERE EXTRACT(YEAR FROM P.FECHA_NACIMIENTO)>2000;

--Apartado 10
UPDATE PERSONA SET NOMBRE=UPPER(NOMBRE); -- NO SE ENLAZAR LA CONSULTA CON LA ACTUALIZACION
SELECT P.NOMBRE 
FROM ALUMNO a , PERSONA p 
WHERE A.DNI = P.DNI ;