CREATE TABLE FABRICANTES
(
COD_FABRICANTE NUMBER(3),
NOMBRE VARCHAR2(15),
PAIS VARCHAR2(15),
CONSTRAINT PK_FABRICANTES PRIMARY KEY (COD_FABRICANTE),
CONSTRAINT CHK1_PAIS CHECK (PAIS=UPPER(PAIS))
);


CREATE TABLE ARTICULOS
(
ARTICULO VARCHAR2(20),
COD_FABRICANTE NUMBER(3),
PESO NUMBER(3),
CATEGORIA VARCHAR2(10),
PRECIO_VENTA NUMBER(4,2),
PRECIO_COSTO NUMBER(4,2),
EXISTENCIAS NUMBER(5),
CONSTRAINT PK_ARTICULOS PRIMARY KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
CONSTRAINT FK_COD_FABRICANTE FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE) ON DELETE CASCADE,
CONSTRAINT CHK1_PRECIO_VENTA CHECK (PRECIO_VENTA > 0),
CONSTRAINT CHK2_PRECIO_COSTO CHECK (PRECIO_COSTO > 0),
CONSTRAINT CHK3_PESO CHECK (PESO > 0),
CONSTRAINT CHK4_CATEGORIA CHECK (CATEGORIA IN ('PRIMERA','SEGUNDA','TERCERA'))
);

CREATE TABLE TIENDAS
(
NIF VARCHAR2(10),
NOMBRE VARCHAR2(20),
DIRECCION VARCHAR2(20),
POBLACION VARCHAR2(20),
PROVINCIA VARCHAR2(20),
CODPOSTAL NUMBER(5),
CONSTRAINT PK_TIENDAS PRIMARY KEY (NIF),
CONSTRAINT CHK1_PROVINCIA CHECK (PROVINCIA=UPPER(PROVINCIA))
);

CREATE TABLE PEDIDOS
(
NIF VARCHAR2(10)L,
ARTICULO VARCHAR2(20),
COD_FABRICANTE NUMBER(3),
PESO NUMBER(3),
CATEGORIA VARCHAR2(10),
FECHA_PEDIDO DATE NOT NULL,
UNIDADES_PEDIDAS NUMBER(4),
CONSTRAINT PK_PEDIDOS PRIMARY KEY (NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_PEDIDO),
CONSTRAINT FK1_COD_FABRICANTE FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
CONSTRAINT FK2_ARTICULO FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) ON DELETE CASCADE,
CONSTRAINT FK6_NIF FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF),
CONSTRAINT CHK1_UNIDADES_PEDIDAS CHECK (UNIDADES_PEDIDAS>0)
);

CREATE TABLE VENTAS 
(
NIF VARCHAR2(10) NOT NULL,
ARTICULO VARCHAR2(20) NOT NULL,
COD_FABRICANTE NUMBER(3) NOT NULL,
PESO NUMBER(3) NOT NULL,
CATEGORIA VARCHAR2(10) NOT NULL,
FECHA_VENTA DATE DEFAULT SYSDATE,
UNIDADES_VENDIDAS NUMBER(4),
CONSTRAINT PK_VENTAS PRIMARY KEY (NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_VENTA),
CONSTRAINT FK2_COD_FABRICANTE FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
CONSTRAINT FK_NIF FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF),
CONSTRAINT CHK1_UNIDADES_VENDIDAS CHECK (UNIDADES_VENDIDAS > 0),
CONSTRAINT FK_GRUPO FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) ON DELETE CASCADE
);

ALTER TABLE VENTAS MODIFY UNIDADES_VENDIDAS NUMBER(6);
ALTER TABLE PEDIDOS MODIFY UNIDADES_PEDIDAS NUMBER(6);
ALTER TABLE PEDIDOS ADD PVP_ARTICULO NUMBER(6);
ALTER TABLE VENTAS ADD PVP_ARTICULO NUMBER(6);
ALTER TABLE FABRICANTES DROP COLUMN PAIS;
ALTER TABLE VENTAS ADD CONSTRAINT CHK_UNIDADES_VENDIDAS CHECK (UNIDADES_VENDIDAS>=100);
ALTER TABLE VENTAS DROP CONSTRAINT CHK_UNIDADES_VENDIDAS;
DROP TABLE VENTAS CASCADE CONSTRAINTS; 
DROP TABLE PEDIDOS CASCADE CONSTRAINTS;
DROP TABLE TIENDAS CASCADE CONSTRAINTS;
DROP TABLE ARTICULOS CASCADE CONSTRAINTS;
DROP TABLE FABRICANTES CASCADE CONSTRAINTS;

