CREATE TABLE FABRICANTE(
CODIGO INTEGER(10) AUTO_INCREMENT,
NOMBRE VARCHAR(100),
CONSTRAINT PK_FABRICANTE PRIMARY KEY (CODIGO)
);

CREATE TABLE PRODUCTO(
CODIGO INTEGER(10) AUTO_INCREMENT,
NOMBRE VARCHAR(100),
PRECIO DOUBLE(12,2),
CODIGO_FABRICANTE INTEGER(10),
CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO),
CONSTRAINT FK1_CODIGO FOREIGN KEY (CODIGO_FABRICANTE) REFERENCES FABRICANTE(CODIGO)
);

INSERT INTO FABRICANTE 
VALUES (1, 'ASUS');

INSERT INTO FABRICANTE 
VALUES (2, 'LENOVO');

INSERT INTO FABRICANTE 
VALUES (3, 'HEWLETT-PACKARD');

INSERT INTO FABRICANTE 
VALUES (4, 'SAMSUNG');

INSERT INTO FABRICANTE 
VALUES (5, 'SEAGATE');

INSERT INTO FABRICANTE 
VALUES (6, 'CRUCIAL');

INSERT INTO FABRICANTE 
VALUES (7, 'GIGABYTE');

INSERT INTO FABRICANTE 
VALUES (8, 'HUAWEI');

INSERT INTO FABRICANTE 
VALUES (9, 'XIAOMI');

INSERT INTO PRODUCTO 
VALUES (1, 'DISCO DURO SATA 3 1TB', 86.99, 5);

INSERT INTO PRODUCTO 
VALUES (2, 'MEMORIA RAM DDR4 8GB', 120, 6);

INSERT INTO PRODUCTO 
VALUES (3, 'DISCO SSD 1 TB', 150.99, 4);

INSERT INTO PRODUCTO 
VALUES (4, 'GEFORCE GTX 1050TI', 185, 7);

INSERT INTO PRODUCTO
VALUES (5, 'GeForce GTX 1080 Xtreme', 755, 6);

INSERT INTO PRODUCTO 
VALUES (6, 'Monitor 24 LED Full HD', 202, 1);

INSERT INTO PRODUCTO 
VALUES (7, 'Monitor 27 LED Full HD', 245.99, 1);

INSERT INTO PRODUCTO 
VALUES (8, 'Portátil Yoga 520', 559, 2);

INSERT INTO PRODUCTO 
VALUES (9, 'Portátil Ideapd 320', 444, 2);

INSERT INTO PRODUCTO 
VALUES (10, 'Impresora HP Deskjet 3720', 59.99, 3);

INSERT INTO PRODUCTO 
VALUES (11, 'Impresora HP Laserjet Pro M26nw', 180, 3);

INSERT INTO FABRICANTE 
VALUES (10, 'MSI');


INSERT INTO fabricante (nombre)
VALUES ('Acer')
/*RETURNING codigo INTO :codigo; Al ser codigo PK necesita introducir
obligatoriamente el codigo, esto es lo mas parecido que he encontrado
para meter solo nombre, pero al final termina pidiendo la PK*/

INSERT INTO PRODUCTO  
VALUES (12, 'LAPTOP GT72-2QD', 1600, 10);

/*INSERT INTO PRODUCTO (NOMBRE, PRECIO, CODIGO_FABRICANTE) 
VALUES ('LAPTOP GF75', 1079, 10); NO DEJA INSERTAR CON NULL EN PK*/

ALTER TABLE PRODUCTO DROP FOREIGN KEY FK1_CODIGO;

ALTER TABLE FABRICANTE DROP PRIMARY KEY;

DELETE FROM FABRICANTE WHERE NOMBRE LIKE 'ASUS';
DELETE FROM FABRICANTE WHERE NOMBRE LIKE 'XIAOMI';
UPDATE FABRICANTE SET CODIGO=20 WHERE (NOMBRE) LIKE ('LENOVO');
UPDATE FABRICANTE SET CODIGO=30 WHERE (NOMBRE) LIKE ('HUAWEI');
UPDATE PRODUCTO SET PRECIO=PRECIO+5;
DELETE FROM PRODUCTO WHERE UPPER(NOMBRE) LIKE 'IMPRESORA%' AND precio < 200;

ALTER TABLE FABRICANTE ADD CONSTRAINT PK1_FABRICANTE PRIMARY KEY (CODIGO);
DELETE FROM PRODUCTO WHERE CODIGO_FABRICANTE NOT IN (SELECT CODIGO FROM FABRICANTE);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK1_CODIGO FOREIGN KEY (CODIGO_FABRICANTE) REFERENCES FABRICANTE(CODIGO);

