DROP TABLE VEHICULOS;
DROP TABLE ALQUILERES;
DROP TABLE CLIENTES;

CREATE TABLE VEHICULOS(
MATRICULA VARCHAR2(7),
MARCA VARCHAR2(10) NOT NULL,
MODELO VARCHAR2(10) NOT NULL,
FECHA_COMPRA DATE,
PRECIO_POR_DIA NUMBER(5,2),
CONSTRAINT PK_VEHICULOS PRIMARY KEY (MATRICULA),
CONSTRAINT CHK1_FECHA CHECK (EXTRACT (YEAR FROM FECHA_COMPRA)>=2001),
CONSTRAINT CHK2_PRECIO_DIA CHECK (PRECIO_POR_DIA > 0)
);

CREATE TABLE CLIENTES(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(30) NOT NULL,
NACIONALIDAD VARCHAR2(30),
FECHA_NACIMIENTO DATE,
DIRECCION VARCHAR2(50),
CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)

);

CREATE TABLE ALQUILERES(
MATRICULA VARCHAR2(7) NOT NULL,
DNI VARCHAR2(10) NOT NULL,
FECHAHORA DATE,
NUM_DIAS NUMBER(2) NOT NULL,
KILOMETROS NUMBER(4) DEFAULT 0,
CONSTRAINT PK_ALQUILERES PRIMARY KEY (MATRICULA, DNI, FECHAHORA),
CONSTRAINT FK1_MATRICULA FOREIGN KEY (MATRICULA) REFERENCES VEHICULOS(MATRICULA),
CONSTRAINT FK2_DNI FOREIGN KEY (DNI) REFERENCES CLIENTES(DNI)
);

ALTER TABLE CLIENTES ADD CONSTRAINT CHK1_DNI CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}-[A-Za-z]$'));
ALTER TABLE VEHICULOS ADD CONSTRAINT CHK3_VEHICULOS CHECK (REGEXP_LIKE(MATRICULA, '^[0-9]{4}[A-Z]{3}$'));
ALTER TABLE VEHICULOS ADD (KILOMETROS NUMBER(5));

